import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ordersService, type OrderInput, type OrderQuery } from '../services/orders.service';

export function useOrders(query: OrderQuery) { return useQuery({ queryKey: ['orders', query], queryFn: () => ordersService.list(query) }); }
export function useOrder(id: string | null) { return useQuery({ queryKey: ['order', id], queryFn: () => ordersService.get(id ?? ''), enabled: Boolean(id) }); }
export function useCreateOrder() { const client = useQueryClient(); return useMutation({ mutationFn: (input: OrderInput) => ordersService.create(input), onSuccess: () => { void client.invalidateQueries({ queryKey: ['orders'] }); void client.invalidateQueries({ queryKey: ['order-counts'] }); } }); }
export function useUpdateOrder() { const client = useQueryClient(); return useMutation({ mutationFn: ({ id, input }: { id: string; input: Partial<OrderInput> }) => ordersService.update({ id, input }), onMutate: async ({ id, input }) => { await client.cancelQueries({ queryKey: ['orders'] }); const snapshots = client.getQueriesData<{ data: import('../services/orders.service').Order[] }>({ queryKey: ['orders'] }); snapshots.forEach(([key, data]) => { if (data) client.setQueryData(key, { ...data, data: data.data.map((order) => order.id === id ? { ...order, ...input } : order) }); }); return { snapshots }; }, onError: (_error, _variables, context) => context?.snapshots.forEach(([key, data]) => client.setQueryData(key, data)), onSettled: () => { void client.invalidateQueries({ queryKey: ['orders'] }); void client.invalidateQueries({ queryKey: ['order'] }); void client.invalidateQueries({ queryKey: ['order-counts'] }); } }); }
export function useDeleteOrder() { const client = useQueryClient(); return useMutation({ mutationFn: ordersService.remove, onSuccess: () => { void client.invalidateQueries({ queryKey: ['orders'] }); void client.invalidateQueries({ queryKey: ['order-counts'] }); } }); }
export function useOrderCounts() { return useQuery({ queryKey: ['order-counts'], queryFn: ordersService.counts }); }
