import { Bell, CakeSlice, CalendarDays, ChevronDown, ClipboardList, HelpCircle, ImagePlus, Images, LayoutDashboard, Mail, Menu, MessageSquareHeart, PanelsTopLeft, Settings, UserRound, X } from 'lucide-react';
import { useState } from 'react';
import { Link, NavLink, Outlet, useLocation } from 'react-router-dom';
import { useAuth } from '../hooks/use-auth';
import { cn } from '../utils/cn';

const nav = [
  ['Dashboard', '/', LayoutDashboard], ['Orders', '/orders', ClipboardList], ['Content', '/content', PanelsTopLeft], ['Events', '/events', CalendarDays], ['Gallery', '/gallery', Images], ['Media Library', '/media', ImagePlus], ['Testimonials', '/testimonials', MessageSquareHeart], ['FAQs', '/faqs', HelpCircle], ['Messages', '/messages', Mail], ['Website Settings', '/settings', Settings],
] as const;
const cakeNav = [['All Cakes', '/cakes'], ['Categories', '/cakes/categories']] as const;

export function DashboardLayout(): React.JSX.Element {
  const [open, setOpen] = useState(false); const { user, signOut } = useAuth(); const location = useLocation();
  const linkClass = ({ isActive }: { isActive: boolean }) => cn('flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-medium transition', isActive ? 'bg-rose text-white shadow-lg' : 'text-[#dbccd2] hover:bg-white/10');
  const sidebar = <aside className="flex h-full w-72 flex-col overflow-y-auto bg-[#342630] px-4 py-6 text-white"><Link to="/" className="mb-10 flex items-center gap-3 px-3 text-xl font-bold"><span className="rounded-xl bg-rose p-2"><CakeSlice /></span><span>Cakes by Shiddat</span></Link><nav className="space-y-1"><NavLink to="/" end onClick={() => setOpen(false)} className={linkClass}><LayoutDashboard className="h-5 w-5" />Dashboard</NavLink><div><div className="flex items-center gap-3 px-3 pb-1 pt-3 text-sm font-medium text-[#dbccd2]"><CakeSlice className="h-5 w-5" />Cakes</div><div className="ml-5 space-y-1 border-l border-white/15 pl-3">{cakeNav.map(([label, path]) => <NavLink key={path} to={path} end onClick={() => setOpen(false)} className={linkClass}>{label}</NavLink>)}</div></div>{nav.slice(1).map(([label, path, Icon]) => <NavLink key={path} to={path} onClick={() => setOpen(false)} className={linkClass}><Icon className="h-5 w-5" />{label}</NavLink>)}</nav><div className="mt-auto rounded-2xl bg-white/10 p-4 text-sm"><p className="font-semibold">Need assistance?</p><p className="mt-1 text-[#dbccd2]">Contact your site team.</p></div></aside>;
  const page = location.pathname === '/cakes/categories' ? 'Categories' : location.pathname === '/cakes' ? 'All Cakes' : nav.find(([, path]) => path === location.pathname)?.[0] ?? 'Profile';
  return <div className="min-h-screen bg-cream"><div className="fixed inset-y-0 left-0 z-40 hidden lg:block">{sidebar}</div>{open && <div className="fixed inset-0 z-50 lg:hidden"><button aria-label="Close menu" onClick={() => setOpen(false)} className="absolute inset-0 bg-black/30" /><div className="relative h-full w-72">{sidebar}<button aria-label="Close menu" onClick={() => setOpen(false)} className="absolute right-4 top-4"><X /></button></div></div>}<div className="lg:pl-72"><header className="sticky top-0 z-30 flex h-20 items-center justify-between border-b border-rose-100 bg-white/90 px-5 backdrop-blur lg:px-8"><div className="flex items-center gap-4"><button aria-label="Open menu" className="lg:hidden" onClick={() => setOpen(true)}><Menu /></button><div><p className="text-xs text-[#9b838d]">Admin / {page}</p><h1 className="text-lg font-bold">{page}</h1></div></div><div className="flex items-center gap-4"><button aria-label="Notifications" className="relative rounded-xl bg-rose-light p-2.5 text-rose"><Bell className="h-5 w-5" /><span className="absolute right-2 top-2 h-2 w-2 rounded-full bg-rose" /></button><details className="relative"><summary className="flex cursor-pointer list-none items-center gap-2"><span className="grid h-9 w-9 place-items-center rounded-full bg-lavender text-sm font-bold text-[#7669a6]">{user?.name?.charAt(0) ?? 'A'}</span><span className="hidden text-sm font-semibold sm:block">{user?.name ?? 'Admin'}</span><ChevronDown className="h-4 w-4" /></summary><div className="absolute right-0 mt-3 w-44 rounded-xl border border-rose-100 bg-white p-2 shadow-xl"><Link to="/profile" className="flex items-center gap-2 rounded-lg px-3 py-2 text-sm hover:bg-rose-light"><UserRound className="h-4 w-4" />Profile</Link><button onClick={signOut} className="w-full rounded-lg px-3 py-2 text-left text-sm text-rose hover:bg-rose-light">Logout</button></div></details></div></header><main className="p-5 lg:p-8"><Outlet /></main></div></div>;
}
