import { useState } from 'react';
import { CakeFormModal } from '../components/cake-form-modal';
import { Button, Card, Input } from '../components/ui';
import { useCakes, useDeleteCake } from '../hooks/use-cakes';
import type { Cake } from '../services/cakes.service';

export function CakesPage(): React.JSX.Element {
  const [search, setSearch] = useState(''); const [page, setPage] = useState(1); const [sort, setSort] = useState<'displayOrder' | 'createdAt' | 'name'>('displayOrder'); const [editing, setEditing] = useState<Cake | null | 'new'>(null); const [notice, setNotice] = useState(''); const cakes = useCakes({ page, limit: 10, search, sort, sortOrder: 'asc' }); const remove = useDeleteCake();
  return <><div className="mb-7 flex items-end justify-between"><div><h2 className="text-2xl font-bold">Cakes</h2><p className="text-[#806c75]">Published cake catalogue.</p></div><Button onClick={() => setEditing('new')}>New cake</Button></div>{notice && <p className="mb-4 text-sm text-emerald-700">{notice}</p>}<Card className="p-0"><div className="flex gap-3 border-b p-5"><Input value={search} onChange={(event) => { setSearch(event.target.value); setPage(1); }} placeholder="Search cakes" /><select value={sort} onChange={(event) => setSort(event.target.value as typeof sort)} className="rounded-xl border px-3"><option value="displayOrder">Display order</option><option value="createdAt">Newest</option><option value="name">Name</option></select></div><div className="divide-y">{cakes.isLoading ? <p className="p-8">Loading cakes…</p> : cakes.data?.items.map((cake) => <div key={cake.id} className="flex items-center gap-4 p-4"><img src={cake.coverMedia.secureUrl} alt={cake.name} className="h-14 w-14 rounded-xl object-cover" /><div className="flex-1"><b>{cake.name}</b><p className="text-sm text-[#806c75]">{cake.category.name} · {cake.slug}</p></div><Button className="bg-rose-light text-rose" onClick={() => setEditing(cake)}>Edit</Button><button onClick={() => remove.mutate(cake.id, { onSuccess: () => setNotice('Cake deleted.') })} className="text-red-700">Delete</button></div>)}{!cakes.isLoading && !cakes.data?.items.length && <p className="p-8 text-center">No published cakes found.</p>}</div><div className="flex justify-end gap-3 border-t p-4"><Button disabled={page === 1} onClick={() => setPage(page - 1)}>Previous</Button><span className="p-2">{page} / {cakes.data?.pagination.totalPages ?? 1}</span><Button disabled={page === (cakes.data?.pagination.totalPages ?? 1)} onClick={() => setPage(page + 1)}>Next</Button></div></Card>{editing && <CakeFormModal cake={editing === 'new' ? null : editing} onClose={() => setEditing(null)} onComplete={(message) => { setNotice(message); if (!message.startsWith('Could')) setEditing(null); }} />}</>;
}
