import { zodResolver } from '@hookform/resolvers/zod';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { LoaderCircle, Save } from 'lucide-react';
import { useEffect, useState } from 'react';
import { useForm, type FieldPath } from 'react-hook-form';
import { z } from 'zod';
import { MediaPicker } from '../components/media-picker';
import { Button, Card, Input, Textarea } from '../components/ui';
import { settingsService, type UpdateWebsiteSettings } from '../services/content.service';

const optionalUrl = z.union([z.literal(''), z.url()]);
const settingsSchema = z.object({ businessName: z.string().trim().min(1, 'Business name is required'), tagline: z.string(), description: z.string(), phone: z.string(), whatsapp: z.string(), email: z.union([z.literal(''), z.email('Enter a valid email')]), address: z.string(), instagram: optionalUrl, facebook: optionalUrl, youtube: optionalUrl, heroTitle: z.string(), heroSubtitle: z.string(), heroButtonText: z.string(), footerText: z.string(), googleMapsUrl: optionalUrl, seoTitle: z.string(), seoDescription: z.string(), logoUrl: optionalUrl, faviconUrl: optionalUrl });
type SettingsFormValues = z.infer<typeof settingsSchema>;
const emptySettings: SettingsFormValues = { businessName: '', tagline: '', description: '', phone: '', whatsapp: '', email: '', address: '', instagram: '', facebook: '', youtube: '', heroTitle: '', heroSubtitle: '', heroButtonText: '', footerText: '', googleMapsUrl: '', seoTitle: '', seoDescription: '', logoUrl: '', faviconUrl: '' };
const sections: Array<{ title: string; fields: Array<{ name: FieldPath<SettingsFormValues>; label: string; type?: 'email' | 'url' | 'textarea' }> }> = [{ title: 'Business Information', fields: [{ name: 'businessName', label: 'Business name' }, { name: 'tagline', label: 'Tagline' }, { name: 'description', label: 'Description', type: 'textarea' }] }, { title: 'Contact', fields: [{ name: 'phone', label: 'Phone' }, { name: 'whatsapp', label: 'WhatsApp number' }, { name: 'email', label: 'Email', type: 'email' }, { name: 'address', label: 'Address', type: 'textarea' }, { name: 'googleMapsUrl', label: 'Google Maps embed URL', type: 'url' }] }, { title: 'Social Links', fields: [{ name: 'instagram', label: 'Instagram URL', type: 'url' }, { name: 'facebook', label: 'Facebook URL', type: 'url' }, { name: 'youtube', label: 'YouTube URL', type: 'url' }] }, { title: 'Homepage', fields: [{ name: 'heroTitle', label: 'Hero title', type: 'textarea' }, { name: 'heroSubtitle', label: 'Hero subtitle', type: 'textarea' }, { name: 'heroButtonText', label: 'Hero button text' }, { name: 'footerText', label: 'Footer text', type: 'textarea' }] }, { title: 'SEO', fields: [{ name: 'seoTitle', label: 'SEO title' }, { name: 'seoDescription', label: 'SEO description', type: 'textarea' }] }];

export function SettingsPage(): React.JSX.Element {
  const queryClient = useQueryClient(); const [notice, setNotice] = useState<{ type: 'success' | 'error'; message: string } | null>(null); const [pickerTarget, setPickerTarget] = useState<'logoUrl' | 'faviconUrl' | null>(null);
  const { data, isLoading, isError } = useQuery({ queryKey: ['settings'], queryFn: settingsService.get });
  const { register, handleSubmit, reset, setValue, watch, formState: { errors } } = useForm<SettingsFormValues>({ resolver: zodResolver(settingsSchema), defaultValues: emptySettings });
  useEffect(() => { if (data) reset(data); }, [data, reset]);
  const mutation = useMutation({ mutationFn: settingsService.update, onSuccess: (settings) => { queryClient.setQueryData(['settings'], settings); setNotice({ type: 'success', message: 'Website settings saved.' }); }, onError: () => setNotice({ type: 'error', message: 'Could not save settings. Please try again.' }) });
  if (isLoading) return <div className="flex min-h-64 items-center justify-center text-[#806c75]"><LoaderCircle className="mr-2 animate-spin" /> Loading website settings…</div>;
  if (isError) return <Card><p className="text-red-700">Unable to load website settings. Refresh the page to try again.</p></Card>;
  return <><div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-2xl font-bold">Website Settings</h2><p className="mt-1 text-[#806c75]">Manage the content shown across your public website.</p></div>{notice && <p role="status" className={notice.type === 'success' ? 'text-sm font-medium text-emerald-700' : 'text-sm font-medium text-red-700'}>{notice.message}</p>}</div><form onSubmit={handleSubmit((values) => mutation.mutate(values as UpdateWebsiteSettings))} className="grid gap-6">{sections.map((section) => <Card key={section.title}><h3 className="mb-5 text-lg font-bold">{section.title}</h3><div className="grid gap-5 sm:grid-cols-2">{section.fields.map((field) => <label key={field.name} className={field.type === 'textarea' ? 'text-sm font-semibold sm:col-span-2' : 'text-sm font-semibold'}>{field.label}{field.type === 'textarea' ? <Textarea rows={4} className="mt-2" {...register(field.name)} /> : <Input type={field.type} className="mt-2" {...register(field.name)} />}{errors[field.name] && <span className="mt-1 block text-xs font-medium text-red-700">{errors[field.name]?.message}</span>}</label>)}</div></Card>)}<Card><h3 className="mb-2 text-lg font-bold">Branding</h3><p className="mb-5 text-sm text-[#806c75]">Choose your logo and favicon from the shared Media Library.</p><div className="grid gap-5 sm:grid-cols-2">{(['logoUrl', 'faviconUrl'] as const).map((field) => <div key={field} className="rounded-2xl border border-rose-100 p-4"><p className="font-semibold">{field === 'logoUrl' ? 'Logo' : 'Favicon'}</p>{watch(field) ? <img src={watch(field)} alt={`${field === 'logoUrl' ? 'Logo' : 'Favicon'} preview`} className="mt-3 h-24 w-24 rounded-xl border border-rose-100 object-contain" /> : <p className="mt-3 text-sm text-[#806c75]">No image selected.</p>}<Button type="button" className="mt-4" onClick={() => setPickerTarget(field)}>Select from Media Library</Button></div>)}</div></Card><div className="sticky bottom-4 flex justify-end"><Button type="submit" disabled={mutation.isPending}><Save size={18} />{mutation.isPending ? 'Saving…' : 'Save settings'}</Button></div></form><MediaPicker open={pickerTarget !== null} title={pickerTarget === 'logoUrl' ? 'Choose logo' : 'Choose favicon'} onClose={() => setPickerTarget(null)} onSelect={(media) => { if (pickerTarget) setValue(pickerTarget, media.secureUrl, { shouldDirty: true, shouldValidate: true }); }} /></>;
}
