import { PartialType } from '@nestjs/swagger';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { Type } from 'class-transformer';
import { ArrayUnique, IsArray, IsBoolean, IsIn, IsInt, IsNotEmpty, IsOptional, IsString, MaxLength, Min, ValidateNested } from 'class-validator';

const sectionTypes = ['hero', 'text', 'cards', 'gallery', 'founders', 'timeline', 'cta', 'faq'] as const;
export class PageSectionItemDto { @ApiPropertyOptional() @IsOptional() @IsString() title?: string; @ApiPropertyOptional() @IsOptional() @IsString() subtitle?: string; @ApiPropertyOptional() @IsOptional() @IsString() description?: string; @ApiPropertyOptional() @IsOptional() @IsString() mediaId?: string; @ApiPropertyOptional() @IsOptional() @IsString() link?: string; @ApiPropertyOptional() @IsOptional() @Type(() => Number) @IsInt() @Min(0) displayOrder?: number; @ApiPropertyOptional() @IsOptional() @Type(() => Boolean) @IsBoolean() active?: boolean; }
export class PageSectionDto { @ApiProperty({ enum: sectionTypes }) @IsIn(sectionTypes) type: typeof sectionTypes[number]; @ApiPropertyOptional() @IsOptional() @IsString() title?: string; @ApiPropertyOptional() @IsOptional() @IsString() subtitle?: string; @ApiPropertyOptional() @IsOptional() @IsString() description?: string; @ApiPropertyOptional() @IsOptional() @IsString() mediaId?: string; @ApiPropertyOptional() @IsOptional() @IsString() buttonText?: string; @ApiPropertyOptional() @IsOptional() @IsString() buttonUrl?: string; @ApiPropertyOptional() @IsOptional() @Type(() => Number) @IsInt() @Min(0) displayOrder?: number; @ApiPropertyOptional() @IsOptional() @Type(() => Boolean) @IsBoolean() active?: boolean; @ApiPropertyOptional({ type: [PageSectionItemDto] }) @IsOptional() @IsArray() @ValidateNested({ each: true }) @Type(() => PageSectionItemDto) items?: PageSectionItemDto[]; }
export class CreatePageDto { @ApiProperty() @IsString() @IsNotEmpty() @MaxLength(100) slug: string; @ApiPropertyOptional() @IsOptional() @IsString() title?: string; @ApiPropertyOptional() @IsOptional() @IsString() subtitle?: string; @ApiPropertyOptional() @IsOptional() @IsString() heroMediaId?: string; @ApiPropertyOptional() @IsOptional() @IsString() seoTitle?: string; @ApiPropertyOptional() @IsOptional() @IsString() seoDescription?: string; @ApiPropertyOptional() @IsOptional() @Type(() => Boolean) @IsBoolean() published?: boolean; @ApiPropertyOptional() @IsOptional() @Type(() => Number) @IsInt() @Min(0) displayOrder?: number; @ApiPropertyOptional({ type: [PageSectionDto] }) @IsOptional() @IsArray() @ValidateNested({ each: true }) @Type(() => PageSectionDto) sections?: PageSectionDto[]; }
export class UpdatePageDto extends PartialType(CreatePageDto) {}
