import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { Prisma, PrismaClient } from '@prisma/client';
import { PrismaService } from '../prisma/prisma.service';
import { PaginatedResponse, paginationMeta } from '../common/dto/pagination-query.dto';
import { CakeCategoryQueryDto, CakeMediaDto, CakeQueryDto, CreateCakeCategoryDto, CreateCakeDto, PublicCakeQueryDto, UpdateCakeCategoryDto, UpdateCakeDto } from './dto/cake.dto';

const categoryInclude = { coverMedia: true, _count: { select: { cakes: true } } } satisfies Prisma.CakeCategoryInclude;
const cakeInclude = { category: true, coverMedia: true, prices: { orderBy: { displayOrder: 'asc' } }, flavors: { orderBy: { displayOrder: 'asc' } }, gallery: { orderBy: { displayOrder: 'asc' }, include: { media: true } } } satisfies Prisma.CakeInclude;
type CategoryResult = Prisma.CakeCategoryGetPayload<{ include: typeof categoryInclude }>;
type CakeResult = Prisma.CakeGetPayload<{ include: typeof cakeInclude }>;
type DbClient = PrismaService | Prisma.TransactionClient;
const publicCategorySelect = { id: true, name: true, slug: true, description: true, coverMedia: { select: { id: true, secureUrl: true, alt: true } } } satisfies Prisma.CakeCategorySelect;
const publicCakeSelect = { id: true, name: true, slug: true, shortDescription: true, description: true, featured: true, bestSeller: true, newArrival: true, trending: true, eggOption: true, seoTitle: true, seoDescription: true, displayOrder: true, coverMedia: { select: { id: true, secureUrl: true, alt: true } }, category: { select: publicCategorySelect }, prices: { select: { id: true, weight: true, price: true, displayOrder: true }, orderBy: { displayOrder: 'asc' } }, flavors: { select: { id: true, name: true, displayOrder: true }, orderBy: { displayOrder: 'asc' } }, gallery: { select: { mediaId: true, displayOrder: true, media: { select: { id: true, secureUrl: true, alt: true } } }, orderBy: { displayOrder: 'asc' } } } satisfies Prisma.CakeSelect;
type PublicCakeResult = Prisma.CakeGetPayload<{ select: typeof publicCakeSelect }>;
type PublicCategoryResult = Prisma.CakeCategoryGetPayload<{ select: typeof publicCategorySelect }>;

@Injectable()
export class CakesService {
  constructor(private readonly prisma: PrismaService) {}

  private async categoryExists(categoryId: string, db: DbClient = this.prisma): Promise<void> { if (!await db.cakeCategory.findUnique({ where: { id: categoryId }, select: { id: true } })) throw new BadRequestException('Cake category not found'); }
  private async mediaExists(mediaId: string, field: string, db: DbClient = this.prisma): Promise<void> { if (!await db.media.findUnique({ where: { id: mediaId }, select: { id: true } })) throw new BadRequestException(`${field} media was not found`); }
  private async validateMediaReferences(coverMediaId: string | undefined, gallery: CakeMediaDto[] | undefined, db: DbClient = this.prisma): Promise<void> { if (coverMediaId) await this.mediaExists(coverMediaId, 'Cover', db); if (gallery?.length) { const ids = gallery.map(({ mediaId }) => mediaId); const count = await db.media.count({ where: { id: { in: ids } } }); if (count !== ids.length) throw new BadRequestException('One or more gallery media items were not found'); } }
  private async categoryOrThrow(id: string): Promise<CategoryResult> { const category = await this.prisma.cakeCategory.findUnique({ where: { id }, include: categoryInclude }); if (!category) throw new NotFoundException('Cake category not found'); return category; }
  private async cakeOrThrow(id: string): Promise<CakeResult> { const cake = await this.prisma.cake.findUnique({ where: { id }, include: cakeInclude }); if (!cake) throw new NotFoundException('Cake not found'); return cake; }
  private async ensureCategorySlug(slug: string, exceptId?: string): Promise<void> { const existing = await this.prisma.cakeCategory.findFirst({ where: { slug, ...(exceptId ? { id: { not: exceptId } } : {}) }, select: { id: true } }); if (existing) throw new BadRequestException('Cake category slug already exists'); }
  private async ensureCakeSlug(slug: string, exceptId?: string): Promise<void> { const existing = await this.prisma.cake.findFirst({ where: { slug, ...(exceptId ? { id: { not: exceptId } } : {}) }, select: { id: true } }); if (existing) throw new BadRequestException('Cake slug already exists'); }

  async createCategory(dto: CreateCakeCategoryDto): Promise<CategoryResult> { await this.ensureCategorySlug(dto.slug); if (dto.coverMediaId) await this.mediaExists(dto.coverMediaId, 'Cover'); return this.prisma.cakeCategory.create({ data: dto, include: categoryInclude }); }
  async findAllCategories(query: CakeCategoryQueryDto): Promise<PaginatedResponse<CategoryResult>> { const where: Prisma.CakeCategoryWhereInput = { ...(query.active === undefined ? {} : { active: query.active }), ...(query.search ? { OR: [{ name: { contains: query.search, mode: 'insensitive' } }, { slug: { contains: query.search, mode: 'insensitive' } }, { description: { contains: query.search, mode: 'insensitive' } }] } : {}) }; const orderBy: Prisma.CakeCategoryOrderByWithRelationInput[] = [{ [query.sortBy]: query.sortOrder }, ...(query.sortBy === 'displayOrder' ? [{ name: 'asc' as const }] : [])]; const [data, total] = await this.prisma.$transaction([this.prisma.cakeCategory.findMany({ where, include: categoryInclude, skip: (query.page - 1) * query.limit, take: query.limit, orderBy }), this.prisma.cakeCategory.count({ where })]); return { data, meta: paginationMeta(query.page, query.limit, total) }; }
  findOneCategory(id: string): Promise<CategoryResult> { return this.categoryOrThrow(id); }
  async updateCategory(id: string, dto: UpdateCakeCategoryDto): Promise<CategoryResult> { await this.categoryOrThrow(id); if (dto.slug) await this.ensureCategorySlug(dto.slug, id); if (dto.coverMediaId) await this.mediaExists(dto.coverMediaId, 'Cover'); return this.prisma.cakeCategory.update({ where: { id }, data: dto, include: categoryInclude }); }
  async removeCategory(id: string): Promise<void> { const category = await this.categoryOrThrow(id); if (category._count.cakes > 0) throw new BadRequestException('Cannot delete a category that contains cakes'); await this.prisma.cakeCategory.delete({ where: { id } }); }

  async create(dto: CreateCakeDto): Promise<CakeResult> { await this.categoryExists(dto.categoryId); await this.ensureCakeSlug(dto.slug); await this.validateMediaReferences(dto.coverMediaId, dto.gallery); return this.prisma.cake.create({ data: { categoryId: dto.categoryId, name: dto.name, slug: dto.slug, shortDescription: dto.shortDescription, description: dto.description, featured: dto.featured, bestSeller: dto.bestSeller, newArrival: dto.newArrival, trending: dto.trending, eggOption: dto.eggOption, status: dto.status, displayOrder: dto.displayOrder, seoTitle: dto.seoTitle, seoDescription: dto.seoDescription, coverMediaId: dto.coverMediaId, prices: dto.prices ? { create: dto.prices } : undefined, flavors: dto.flavors ? { create: dto.flavors } : undefined, gallery: dto.gallery ? { create: dto.gallery } : undefined }, include: cakeInclude }); }
  async findAll(query: CakeQueryDto): Promise<PaginatedResponse<CakeResult>> { const where: Prisma.CakeWhereInput = { ...(query.categoryId ? { categoryId: query.categoryId } : {}), ...(query.featured === undefined ? {} : { featured: query.featured }), ...(query.status ? { status: query.status } : {}), ...(query.search ? { OR: [{ name: { contains: query.search, mode: 'insensitive' } }, { slug: { contains: query.search, mode: 'insensitive' } }, { shortDescription: { contains: query.search, mode: 'insensitive' } }, { description: { contains: query.search, mode: 'insensitive' } }] } : {}) }; const sortBy = query.newest ? 'createdAt' : query.sortBy; const sortOrder = query.newest ? 'desc' : query.sortOrder; const orderBy: Prisma.CakeOrderByWithRelationInput[] = [{ [sortBy]: sortOrder }, ...(sortBy === 'displayOrder' ? [{ name: 'asc' as const }] : [])]; const [data, total] = await this.prisma.$transaction([this.prisma.cake.findMany({ where, include: cakeInclude, skip: (query.page - 1) * query.limit, take: query.limit, orderBy }), this.prisma.cake.count({ where })]); return { data, meta: paginationMeta(query.page, query.limit, total) }; }
  findOne(id: string): Promise<CakeResult> { return this.cakeOrThrow(id); }
  async update(id: string, dto: UpdateCakeDto): Promise<CakeResult> { await this.cakeOrThrow(id); if (dto.categoryId) await this.categoryExists(dto.categoryId); if (dto.slug) await this.ensureCakeSlug(dto.slug, id); await this.validateMediaReferences(dto.coverMediaId, dto.gallery); return this.prisma.$transaction(async (tx) => { if (dto.prices !== undefined) await tx.cakePrice.deleteMany({ where: { cakeId: id } }); if (dto.flavors !== undefined) await tx.cakeFlavor.deleteMany({ where: { cakeId: id } }); if (dto.gallery !== undefined) await tx.cakeMedia.deleteMany({ where: { cakeId: id } }); return tx.cake.update({ where: { id }, data: { categoryId: dto.categoryId, name: dto.name, slug: dto.slug, shortDescription: dto.shortDescription, description: dto.description, featured: dto.featured, bestSeller: dto.bestSeller, newArrival: dto.newArrival, trending: dto.trending, eggOption: dto.eggOption, status: dto.status, displayOrder: dto.displayOrder, seoTitle: dto.seoTitle, seoDescription: dto.seoDescription, coverMediaId: dto.coverMediaId, prices: dto.prices !== undefined ? { create: dto.prices } : undefined, flavors: dto.flavors !== undefined ? { create: dto.flavors } : undefined, gallery: dto.gallery !== undefined ? { create: dto.gallery } : undefined }, include: cakeInclude }); }); }
  async remove(id: string): Promise<void> { await this.cakeOrThrow(id); await this.prisma.cake.delete({ where: { id } }); }
  private publicCakeWhere(query?: PublicCakeQueryDto): Prisma.CakeWhereInput { return { status: 'ACTIVE', category: { is: { active: true } }, ...(query?.category ? { category: { is: { active: true, slug: query.category } } } : {}), ...(query?.featured === undefined ? {} : { featured: query.featured }), ...(query?.bestSeller === undefined ? {} : { bestSeller: query.bestSeller }), ...(query?.trending === undefined ? {} : { trending: query.trending }), ...(query?.newArrival === undefined ? {} : { newArrival: query.newArrival }), ...(query?.search ? { OR: [{ name: { contains: query.search, mode: 'insensitive' } }, { slug: { contains: query.search, mode: 'insensitive' } }, { shortDescription: { contains: query.search, mode: 'insensitive' } }, { description: { contains: query.search, mode: 'insensitive' } }] } : {}) }; }
  async findPublicAll(query: PublicCakeQueryDto): Promise<{ items: PublicCakeResult[]; pagination: ReturnType<typeof paginationMeta>; total: number }> { const where = this.publicCakeWhere(query); const orderBy: Prisma.CakeOrderByWithRelationInput[] = [{ [query.sort]: query.sortOrder }, ...(query.sort === 'displayOrder' ? [{ name: 'asc' as const }] : [])]; const [items, total] = await this.prisma.$transaction([this.prisma.cake.findMany({ where, select: publicCakeSelect, skip: (query.page - 1) * query.limit, take: query.limit, orderBy }), this.prisma.cake.count({ where })]); return { items, pagination: paginationMeta(query.page, query.limit, total), total }; }
  async findPublicOne(slug: string): Promise<PublicCakeResult> { const cake = await this.prisma.cake.findFirst({ where: { ...this.publicCakeWhere(), slug }, select: publicCakeSelect }); if (!cake) throw new NotFoundException('Cake not found'); return cake; }
  async findPublicCategories(): Promise<PublicCategoryResult[]> { return this.prisma.cakeCategory.findMany({ where: { active: true }, select: publicCategorySelect, orderBy: [{ displayOrder: 'asc' }, { name: 'asc' }] }); }
  async findPublicCategory(slug: string): Promise<{ category: PublicCategoryResult; cakes: PublicCakeResult[] }> { const category = await this.prisma.cakeCategory.findFirst({ where: { slug, active: true }, select: publicCategorySelect }); if (!category) throw new NotFoundException('Cake category not found'); const cakes = await this.prisma.cake.findMany({ where: this.publicCakeWhere({ category: slug, page: 1, limit: 100, sort: 'displayOrder', sortOrder: 'asc' }), select: publicCakeSelect, orderBy: [{ displayOrder: 'asc' }, { name: 'asc' }] }); return { category, cakes }; }
}
