import { motion } from 'framer-motion';
import { Link } from 'react-router-dom';
import { useCakes } from '../../hooks/use-cakes';
import type { Cake } from '../../services/cakes.service';

const currency = new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 });

function startingPrice(cake: Cake): number | null {
  const prices = cake.prices.map(({ price }) => Number(price)).filter(Number.isFinite);
  return prices.length ? Math.min(...prices) : null;
}

function CakeCard({ cake, index }: { cake: Cake; index: number }): React.JSX.Element {
  const price = startingPrice(cake);
  const badges = [cake.featured && 'Featured', cake.newArrival && 'New', cake.bestSeller && 'Best Seller'].filter(Boolean) as string[];
  return <motion.article initial={{ opacity: 0, y: 24 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.2 }} transition={{ delay: index * 0.08 }} className="group overflow-hidden rounded-[28px] border border-[#f3e5dc] bg-white shadow-sm"><Link to={`/cakes/${cake.slug}`} aria-label={`View ${cake.name}`} className="block overflow-hidden"><img src={cake.coverMedia.secureUrl} alt={cake.coverMedia.alt || cake.name} loading="lazy" width="640" height="480" className="aspect-[4/3] w-full object-cover transition duration-500 group-hover:scale-105" /></Link><div className="p-6"><div className="flex min-h-6 flex-wrap gap-2">{badges.map((badge) => <span key={badge} className="rounded-full bg-[#fff1e9] px-3 py-1 text-[10px] font-semibold uppercase tracking-wider text-[#b97c5d]">{badge}</span>)}</div><p className="mt-3 text-xs font-semibold uppercase tracking-widest text-[#d7a88c]">{cake.category.name}</p><h3 className="mt-2 text-2xl text-[#3a2d28]" style={{ fontFamily: 'Playfair Display' }}>{cake.name}</h3><p className="mt-3 line-clamp-2 min-h-10 text-sm leading-5 text-[#8a7a72]">{cake.shortDescription}</p><div className="mt-6 flex items-center justify-between gap-4">{price === null ? <span className="text-sm text-[#8a7a72]">Price on request</span> : <span className="font-semibold text-[#3a2d28]">From {currency.format(price)}</span>}<Link to={`/cakes/${cake.slug}`} className="rounded-full bg-[#d7a88c] px-5 py-2.5 text-sm font-medium text-white transition hover:bg-[#c99a7d]">View cake</Link></div></div></motion.article>;
}

export function HomeCakesSection(): React.JSX.Element {
  const cakes = useCakes({ page: 1, limit: 6, featured: true, sort: 'displayOrder', sortOrder: 'asc' });
  return <section className="bg-white px-6 py-28"><div className="container-custom"><div className="mb-16 text-center"><p className="mb-4 uppercase tracking-[5px] text-[#d7a88c]">Our Cakes</p><h2 className="text-4xl text-[#3a2d28] md:text-5xl" style={{ fontFamily: 'Playfair Display' }}>Cakes Crafted With Shiddat</h2><p className="mx-auto mt-5 max-w-2xl leading-8 text-[#8a7a72]">Discover a selection of our handcrafted cakes, made for celebrations worth remembering.</p></div>{cakes.isLoading ? <div aria-label="Loading featured cakes" className="grid gap-7 sm:grid-cols-2 lg:grid-cols-3">{Array.from({ length: 3 }, (_, index) => <div key={index} className="overflow-hidden rounded-[28px] border border-[#f3e5dc] bg-white"><div className="aspect-[4/3] animate-pulse bg-[#f3e5dc]" /><div className="space-y-3 p-6"><div className="h-3 w-24 animate-pulse rounded bg-[#f3e5dc]" /><div className="h-7 w-3/4 animate-pulse rounded bg-[#f3e5dc]" /><div className="h-10 animate-pulse rounded bg-[#f3e5dc]" /></div></div>)}</div> : cakes.isError ? <div className="rounded-[28px] border border-[#f3e5dc] bg-[#fff8f2] p-10 text-center"><p className="text-[#8a7a72]">Our featured cakes could not be loaded.</p><button type="button" onClick={() => void cakes.refetch()} className="mt-5 rounded-full bg-[#d7a88c] px-6 py-3 text-white transition hover:bg-[#c99a7d]">Try again</button></div> : cakes.data?.items.length ? <><div className="grid gap-7 sm:grid-cols-2 lg:grid-cols-3">{cakes.data.items.map((cake, index) => <CakeCard key={cake.id} cake={cake} index={index} />)}</div><div className="mt-14 text-center"><Link to="/cakes" className="inline-block rounded-full border border-[#d7a88c] px-8 py-4 text-[#3a2d28] transition hover:bg-[#d7a88c] hover:text-white">Explore all cakes</Link></div></> : <div className="rounded-[28px] border border-[#f3e5dc] bg-[#fff8f2] p-10 text-center"><p className="text-[#8a7a72]">Our featured cake collection is being refreshed.</p><Link to="/cakes" className="mt-5 inline-block rounded-full bg-[#d7a88c] px-6 py-3 text-white">Browse all cakes</Link></div>}</div></section>;
}
